import json
import requests

# blocks = [
#     "<|user|>\nYou are an intelligent AI assistant. Please answer questions based on the user's instructions. Below are some reference documents that may help you in answering the user's question.\n\n",
#     "- Title: Margin Call\nMargin Call is a 2011 American drama film written and directed by J. C. Chandor in his feature directorial debut.The principal story takes place over a 24-hour period at a large Wall Street investment bank during the initial stages of the financial crisis of 2007–08.In focus are the actions taken by a group of employees during the subsequent financial collapse.The ensemble cast features Kevin Spacey, Paul Bettany, Jeremy Irons, Zachary Quinto, Penn Badgley, Simon Baker, Demi Moore, and Stanley Tucci.The film was produced by the production companies Before the Door Pictures (first to sign on, and owned by Zachary Quinto), Benaroya Pictures, as well as Washington Square Films.Theatrically, it was commercially distributed by Lionsgate and Roadside Attractions.\"Margin Call\" explores capitalism, greed, and investment fraud.The director and screenwriter, J. C. Chandor, is himself the son of an investment banker; the screenplay was partially informed by Chandor's own foray into real estate investments in New York City soon before the financial crash.Following its wide release in theaters, the film garnered award nominations from the Detroit Film Critics Society, along with several separate nominations for its screenplay and direction from recognized award organizations, including a nomination for the Academy Award for Best Original Screenplay.The score was orchestrated by musician Nathan Larson.The film made its premiere at the Sundance Film Festival on January 25, 2011, and opened in theaters nationwide in the United States on October 21, 2011, grossing $5,354,039 in domestic ticket receipts.It was screened at 199 theaters during its widest release in cinemas.It earned an additional $14,150,000 in business through international release to top out at a combined $19,504,039 in gross theatrical revenue.It was a ground-breaking day-and-date release that earned more than $10,000,000 in video-on-demand sales during its initial theatrical release.Preceding its theatrical release, \"Margin Call\" was met with positive critical reviews.The DVD and Blu-ray editions of the film were released in the United States on December 20, 2011.\n",
#     "- Title: Nathan Larson\nNathan Peter Larson (born September 12, 1970 in Maryland, U.S.) is an American guitarist, singer, songwriter, and author widely known for his numerous film score compositions.He is married to Nina Persson, the lead singer of the Swedish rock band The Cardigans.In May 2011, Larson's debut novel, \"The Dewey Decimal System\", was published by Akashic Books.The second book in the series was published summer 2012, and is entitled \"The Nervous System.\" The third and final installment in this series, \"The Immune System\", was published in 2015.Larson is responsible for arranging 12 hour experimental music concert events, and is one of the founders of the LUMEN PROJECT.\n",
#     "- Title: Walter Ulfig\nWalter Ulfig was a German composer of film scores.\n",
#     "- Title: Mehdi Abrishamchi\nMehdi Abrishamchi is an Iranian People's Mujahedin of Iran( MEK) politician who has been described as\" the right hand man of Massoud Rajavi\".He is the former spouse of the group's current leader, Maryam Rajavi, whom he divorced so that she could become the spouse of Massoud Rajavi.\n",
#     "- Title: Heather D. Gibson\nHeather Denise Gibson is a Scottish economist currently serving as Director- Advisor to the Bank of Greece( since 2011).She is the spouse of Euclid Tsakalotos, former Greek Minister of Finance.\n",
#     "- Title: Princess Auguste of Bavaria (1875–1964)\nPrincess Auguste of Bavaria( 28 April 1877 – 25 June 1964) was a member of the Bavarian Royal House of Wittelsbach and the spouse of Archduke Joseph August of Austria.\n",
#     "- Title: Maria Teresa, Grand Duchess of Luxembourg\nMaria Teresa, Grand Duchess of Luxembourg( born María Teresa Mestre y Batista; on 22 March 1956), is the spouse of Grand Duke Henri.\n",
#     "- Title: Gertrude of Bavaria\nGertrude of Saxony and Bavaria( 1152/55–1197) was Duchess of Swabia as the spouse of Duke Frederick IV, and Queen of Denmark as the spouse of King Canute VI.\n",
#     "- Title: Marie-Louise Coidavid\nMarie Louise Coidavid( 1778 – March 11, 1851), was the Queen of the Kingdom of Haiti 1811 – 20 as the spouse of Henri I of Haiti.\n",
#     "- Title: Sophia Magdalena of Denmark\nSophia Magdalena of Denmark (3 July 1746 – 21 August 1813) was Queen of Sweden as the spouse of King Gustav III.\n",
#     "Answer the question based on the given passages. Only give me the answer and do not output any other words.\nQuestion: Who is the spouse of the composer of film Margin Call?\n<|assistant|>\n"
# ]

# Qwen
# blocks = [
#     "[Block-Attention]<|im_start|>system\nYou are an intelligent AI assistant. Please answer questions based on the user's instructions. Below are some reference documents that may help you in answering the user's question.\n\n",
#     "- Title: Margin Call\nMargin Call is a 2011 American drama film written and directed by J. C. Chandor in his feature directorial debut.The principal story takes place over a 24-hour period at a large Wall Street investment bank during the initial stages of the financial crisis of 2007–08.In focus are the actions taken by a group of employees during the subsequent financial collapse.The ensemble cast features Kevin Spacey, Paul Bettany, Jeremy Irons, Zachary Quinto, Penn Badgley, Simon Baker, Demi Moore, and Stanley Tucci.The film was produced by the production companies Before the Door Pictures (first to sign on, and owned by Zachary Quinto), Benaroya Pictures, as well as Washington Square Films.Theatrically, it was commercially distributed by Lionsgate and Roadside Attractions.\"Margin Call\" explores capitalism, greed, and investment fraud.The director and screenwriter, J. C. Chandor, is himself the son of an investment banker; the screenplay was partially informed by Chandor's own foray into real estate investments in New York City soon before the financial crash.Following its wide release in theaters, the film garnered award nominations from the Detroit Film Critics Society, along with several separate nominations for its screenplay and direction from recognized award organizations, including a nomination for the Academy Award for Best Original Screenplay.The score was orchestrated by musician Nathan Larson.The film made its premiere at the Sundance Film Festival on January 25, 2011, and opened in theaters nationwide in the United States on October 21, 2011, grossing $5,354,039 in domestic ticket receipts.It was screened at 199 theaters during its widest release in cinemas.It earned an additional $14,150,000 in business through international release to top out at a combined $19,504,039 in gross theatrical revenue.It was a ground-breaking day-and-date release that earned more than $10,000,000 in video-on-demand sales during its initial theatrical release.Preceding its theatrical release, \"Margin Call\" was met with positive critical reviews.The DVD and Blu-ray editions of the film were released in the United States on December 20, 2011.\n",
#     "- Title: Nathan Larson\nNathan Peter Larson (born September 12, 1970 in Maryland, U.S.) is an American guitarist, singer, songwriter, and author widely known for his numerous film score compositions.He is married to Nina Persson, the lead singer of the Swedish rock band The Cardigans.In May 2011, Larson's debut novel, \"The Dewey Decimal System\", was published by Akashic Books.The second book in the series was published summer 2012, and is entitled \"The Nervous System.\" The third and final installment in this series, \"The Immune System\", was published in 2015.Larson is responsible for arranging 12 hour experimental music concert events, and is one of the founders of the LUMEN PROJECT.\n",
#     "- Title: Walter Ulfig\nWalter Ulfig was a German composer of film scores.\n",
#     "- Title: Mehdi Abrishamchi\nMehdi Abrishamchi is an Iranian People's Mujahedin of Iran( MEK) politician who has been described as\" the right hand man of Massoud Rajavi\".He is the former spouse of the group's current leader, Maryam Rajavi, whom he divorced so that she could become the spouse of Massoud Rajavi.\n",
#     "- Title: Heather D. Gibson\nHeather Denise Gibson is a Scottish economist currently serving as Director- Advisor to the Bank of Greece( since 2011).She is the spouse of Euclid Tsakalotos, former Greek Minister of Finance.\n",
#     "- Title: Princess Auguste of Bavaria (1875–1964)\nPrincess Auguste of Bavaria( 28 April 1877 – 25 June 1964) was a member of the Bavarian Royal House of Wittelsbach and the spouse of Archduke Joseph August of Austria.\n",
#     "- Title: Maria Teresa, Grand Duchess of Luxembourg\nMaria Teresa, Grand Duchess of Luxembourg( born María Teresa Mestre y Batista; on 22 March 1956), is the spouse of Grand Duke Henri.\n",
#     "- Title: Gertrude of Bavaria\nGertrude of Saxony and Bavaria( 1152/55–1197) was Duchess of Swabia as the spouse of Duke Frederick IV, and Queen of Denmark as the spouse of King Canute VI.\n",
#     "- Title: Marie-Louise Coidavid\nMarie Louise Coidavid( 1778 – March 11, 1851), was the Queen of the Kingdom of Haiti 1811 – 20 as the spouse of Henri I of Haiti.\n",
#     "- Title: Sophia Magdalena of Denmark\nSophia Magdalena of Denmark (3 July 1746 – 21 August 1813) was Queen of Sweden as the spouse of King Gustav III.\n",
#     "<|im_end|>\n<|im_start|>user\nAnswer the question based on the given passages. Only give me the answer and do not output any other words.\nQuestion: Who is the spouse of the composer of film Margin Call?\n<|im_end|>\n<|im_start|>assistant\n"
# ]

# blocks = [
#     "<|user|>\nYou are an intelligent AI assistant. Please answer questions based on the user's instructions. Below are some reference documents that may help you in answering the user's question.\n\n",
#     "- Title: Scott Derrickson\nScott Derrickson (born July 16, 1966) is an American director, screenwriter and producer. He lives in Los Angeles, California. He is best known for directing horror films such as \"Sinister\", \"The Exorcism of Emily Rose\", and \"Deliver Us From Evil\", as well as the 2016 Marvel Cinematic Universe installment, \"Doctor Strange.\"\n",
#     "- Title: Conrad Brooks\nConrad Brooks (born Conrad Biedrzycki on January 3, 1931 in Baltimore, Maryland) is an American actor. He moved to Hollywood, California in 1948 to pursue a career in acting. He got his start in movies appearing in Ed Wood films such as \"Plan 9 from Outer Space\", \"Glen or Glenda\", and \"Jail Bait.\" He took a break from acting during the 1960s and 1970s but due to the ongoing interest in the films of Ed Wood, he reemerged in the 1980s and has become a prolific actor. He also has since gone on to write, produce and direct several films.\n",
#     "- Title: Ed Wood (film)\nEd Wood is a 1994 American biographical period comedy-drama film directed and produced by Tim Burton, and starring Johnny Depp as cult filmmaker Ed Wood. The film concerns the period in Wood's life when he made his best-known films as well as his relationship with actor Bela Lugosi, played by Martin Landau. Sarah Jessica Parker, Patricia Arquette, Jeffrey Jones, Lisa Marie, and Bill Murray are among the supporting cast.\n",
#     "- Title: Ed Wood\nEdward Davis Wood Jr. (October 10, 1924 – December 10, 1978) was an American filmmaker, actor, writer, producer, and director.\n",
#     "- Title: Adam Collis\nAdam Collis is an American filmmaker and actor. He attended the Duke University from 1986 to 1990 and the University of California, Los Angeles from 2007 to 2010. He also studied cinema at the University of Southern California from 1991 to 1997. Collis first work was the assistant director for the Scott Derrickson's short \"Love in the Ruins\" (1995). In 1998, he played \"Crankshaft\" in Eric Koyanagi's \"Hundred Percent\".\n",
#     "- Title: Doctor Strange (2016 film)\nDoctor Strange is a 2016 American superhero film based on the Marvel Comics character of the same name, produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures. It is the fourteenth film of the Marvel Cinematic Universe (MCU). The film was directed by Scott Derrickson, who wrote it with Jon Spaihts and C. Robert Cargill, and stars Benedict Cumberbatch as Stephen Strange, along with Chiwetel Ejiofor, Rachel McAdams, Benedict Wong, Michael Stuhlbarg, Benjamin Bratt, Scott Adkins, Mads Mikkelsen, and Tilda Swinton. In \"Doctor Strange\", surgeon Strange learns the mystic arts after a career-ending car accident.\n",
#     "- Title: Tyler Bates\nTyler Bates (born June 5, 1965) is an American musician, music producer, and composer for films, television, and video games. Much of his work is in the action and horror film genres, with films like \"Dawn of the Dead, 300, Sucker Punch,\" and \"John Wick.\" He has collaborated with directors like Zack Snyder, Rob Zombie, Neil Marshall, William Friedkin, Scott Derrickson, and James Gunn. With Gunn, he has scored every one of the director's films; including \"Guardians of the Galaxy\", which became one of the highest grossing domestic movies of 2014, and its 2017 sequel. In addition, he is also the lead guitarist of the American rock band Marilyn Manson, and produced its albums \"The Pale Emperor\" and \"Heaven Upside Down\".\n",
#     "- Title: Deliver Us from Evil (2014 film)\nDeliver Us from Evil is a 2014 American supernatural horror film directed by Scott Derrickson and produced by Jerry Bruckheimer. The film is officially based on a 2001 non-fiction book entitled \"Beware the Night\" by Ralph Sarchie and Lisa Collier Cool, and its marketing campaign highlighted that it was \"inspired by actual accounts\". The film stars Eric Bana, Édgar Ramírez, Sean Harris, Olivia Munn, and Joel McHale in the main roles and was released on July 2, 2014.\n",
#     "- Title: Woodson, Arkansas\nWoodson is a census-designated place (CDP) in Pulaski County, Arkansas, in the United States. Its population was 403 at the 2010 census. It is part of the Little Rock–North Little Rock–Conway Metropolitan Statistical Area. Woodson and its accompanying Woodson Lake and Wood Hollow are the namesake for Ed Wood Sr., a prominent plantation owner, trader, and businessman at the turn of the 20th century. Woodson is adjacent to the Wood Plantation, the largest of the plantations own by Ed Wood Sr.\n",
#     "- Title: Sinister (film)\nSinister is a 2012 supernatural horror film directed by Scott Derrickson and written by Derrickson and C. Robert Cargill. It stars Ethan Hawke as fictional true-crime writer Ellison Oswalt who discovers a box of home movies in his attic that puts his family in danger.\n",
#     "Answer the question based on the given passages. The answer should be simple. Questions should give keywords directly, while judgments should give Yes/No answers directly.\nQuestion: Were Scott Derrickson and Ed Wood of the same nationality?\n<|assistant|>\n"
# ]

# Qwen
blocks = [
    "[Block-Attention]<|im_start|>system\nYou are an intelligent AI assistant. Please answer questions based on the user's instructions. Below are some reference documents that may help you in answering the user's question.\n\n",
    "- Title: Scott Derrickson\nScott Derrickson (born July 16, 1966) is an American director, screenwriter and producer. He lives in Los Angeles, California. He is best known for directing horror films such as \"Sinister\", \"The Exorcism of Emily Rose\", and \"Deliver Us From Evil\", as well as the 2016 Marvel Cinematic Universe installment, \"Doctor Strange.\"\n",
    "- Title: Conrad Brooks\nConrad Brooks (born Conrad Biedrzycki on January 3, 1931 in Baltimore, Maryland) is an American actor. He moved to Hollywood, California in 1948 to pursue a career in acting. He got his start in movies appearing in Ed Wood films such as \"Plan 9 from Outer Space\", \"Glen or Glenda\", and \"Jail Bait.\" He took a break from acting during the 1960s and 1970s but due to the ongoing interest in the films of Ed Wood, he reemerged in the 1980s and has become a prolific actor. He also has since gone on to write, produce and direct several films.\n",
    "- Title: Ed Wood (film)\nEd Wood is a 1994 American biographical period comedy-drama film directed and produced by Tim Burton, and starring Johnny Depp as cult filmmaker Ed Wood. The film concerns the period in Wood's life when he made his best-known films as well as his relationship with actor Bela Lugosi, played by Martin Landau. Sarah Jessica Parker, Patricia Arquette, Jeffrey Jones, Lisa Marie, and Bill Murray are among the supporting cast.\n",
    "- Title: Ed Wood\nEdward Davis Wood Jr. (October 10, 1924 – December 10, 1978) was an American filmmaker, actor, writer, producer, and director.\n",
    "- Title: Adam Collis\nAdam Collis is an American filmmaker and actor. He attended the Duke University from 1986 to 1990 and the University of California, Los Angeles from 2007 to 2010. He also studied cinema at the University of Southern California from 1991 to 1997. Collis first work was the assistant director for the Scott Derrickson's short \"Love in the Ruins\" (1995). In 1998, he played \"Crankshaft\" in Eric Koyanagi's \"Hundred Percent\".\n",
    "- Title: Doctor Strange (2016 film)\nDoctor Strange is a 2016 American superhero film based on the Marvel Comics character of the same name, produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures. It is the fourteenth film of the Marvel Cinematic Universe (MCU). The film was directed by Scott Derrickson, who wrote it with Jon Spaihts and C. Robert Cargill, and stars Benedict Cumberbatch as Stephen Strange, along with Chiwetel Ejiofor, Rachel McAdams, Benedict Wong, Michael Stuhlbarg, Benjamin Bratt, Scott Adkins, Mads Mikkelsen, and Tilda Swinton. In \"Doctor Strange\", surgeon Strange learns the mystic arts after a career-ending car accident.\n",
    "- Title: Tyler Bates\nTyler Bates (born June 5, 1965) is an American musician, music producer, and composer for films, television, and video games. Much of his work is in the action and horror film genres, with films like \"Dawn of the Dead, 300, Sucker Punch,\" and \"John Wick.\" He has collaborated with directors like Zack Snyder, Rob Zombie, Neil Marshall, William Friedkin, Scott Derrickson, and James Gunn. With Gunn, he has scored every one of the director's films; including \"Guardians of the Galaxy\", which became one of the highest grossing domestic movies of 2014, and its 2017 sequel. In addition, he is also the lead guitarist of the American rock band Marilyn Manson, and produced its albums \"The Pale Emperor\" and \"Heaven Upside Down\".\n",
    "- Title: Deliver Us from Evil (2014 film)\nDeliver Us from Evil is a 2014 American supernatural horror film directed by Scott Derrickson and produced by Jerry Bruckheimer. The film is officially based on a 2001 non-fiction book entitled \"Beware the Night\" by Ralph Sarchie and Lisa Collier Cool, and its marketing campaign highlighted that it was \"inspired by actual accounts\". The film stars Eric Bana, Édgar Ramírez, Sean Harris, Olivia Munn, and Joel McHale in the main roles and was released on July 2, 2014.\n",
    "- Title: Woodson, Arkansas\nWoodson is a census-designated place (CDP) in Pulaski County, Arkansas, in the United States. Its population was 403 at the 2010 census. It is part of the Little Rock–North Little Rock–Conway Metropolitan Statistical Area. Woodson and its accompanying Woodson Lake and Wood Hollow are the namesake for Ed Wood Sr., a prominent plantation owner, trader, and businessman at the turn of the 20th century. Woodson is adjacent to the Wood Plantation, the largest of the plantations own by Ed Wood Sr.\n",
    "- Title: Sinister (film)\nSinister is a 2012 supernatural horror film directed by Scott Derrickson and written by Derrickson and C. Robert Cargill. It stars Ethan Hawke as fictional true-crime writer Ellison Oswalt who discovers a box of home movies in his attic that puts his family in danger.\n",
    "<|im_end|>\n<|im_start|>user\nAnswer the question based on the given passages. Only give me the answer and do not output any other words.\nQuestion: Were Scott Derrickson and Ed Wood of the same nationality?\n<|im_end|>\n<|im_start|>assistant\n"
]

r = requests.post(
    url="http://127.0.0.1:12345/generate",
    data=json.dumps({"blocks": blocks}),
    headers={"Content-Type": "application/json"}
)

print(r.json()["generated"])